{{ edit_comment }}

FROM rabbitmq:{{ rabbitmq_version }}-{{ rabbitmq_image_type }}

# Labels
# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL "maintainer"="lotyp <lotyp7@gmail.com>"
LABEL "vendor"="wayofdev"
LABEL "org.opencontainers.image.authors"="lotyp <lotyp7@gmail.com>"
LABEL "org.opencontainers.image.url"="https://hub.docker.com/r/wayofdev/rabbitmq"
LABEL "org.opencontainers.image.documentation"="https://github.com/wayofdev/docker-rabbitmq"
LABEL "org.opencontainers.image.source"="https://github.com/wayofdev/docker-rabbitmq"
LABEL "org.opencontainers.image.vendor"="wayofdev"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.ref.name"="{{ rabbitmq_version }}-{{ rabbitmq_image_type }}"
LABEL "org.opencontainers.image.title"="rabbitmq-{{ rabbitmq_version }}-{{ rabbitmq_image_type }}"
LABEL "org.opencontainers.image.description"="rabbitmq-{{ rabbitmq_version }}-{{ rabbitmq_image_type }}"

RUN set -eux; \
    rm -rf /var/cache/apk/* \
    && rm -rf /tmp/* \
    && apk -U upgrade -a \
    && apk add --update --no-cache \
      curl \
      unzip \
{% if true == ext_delayed_message_exchange %}
    && curl -L -o ./rabbitmq_delayed_message_exchange.zip "https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/{{ ext_versions.delayed_message_exchange }}/rabbitmq_delayed_message_exchange-{{ ext_versions.delayed_message_exchange }}.ez" \
        && unzip rabbitmq_delayed_message_exchange.zip \
        && rm -f rabbitmq_delayed_message_exchange.zip \
        && mv rabbitmq_delayed_message_exchange-{{ ext_versions.delayed_message_exchange }} plugins/ \
        && rabbitmq-plugins enable rabbitmq_delayed_message_exchange \
{% endif %}
{% if true == ext_message_timestamp %}
    && curl -L -o ./rabbitmq_message_timestamp.zip "https://github.com/rabbitmq/rabbitmq-message-timestamp/releases/download/v{{ ext_versions.message_timestamp }}/rabbitmq_message_timestamp-{{ ext_versions.message_timestamp }}.ez" \
        && unzip rabbitmq_message_timestamp.zip \
        && rm -f rabbitmq_message_timestamp.zip \
        && mv rabbitmq_message_timestamp-{{ ext_versions.message_timestamp }} plugins/ \
        && rabbitmq-plugins enable rabbitmq_message_timestamp \
{% endif %}
{% if 'management-alpine' == rabbitmq_image_type %}
    && rabbitmq-plugins enable --offline rabbitmq_shovel_management \
{% endif %}
{% if true == ext_amqp1_0 %}
    && rabbitmq-plugins enable rabbitmq_amqp1_0 \
{% endif %}
{% if true == ext_shovel %}
    && rabbitmq-plugins enable --offline rabbitmq_shovel \
{% endif %}
    && apk del -f \
        curl \
        unzip
